### PR TITLE
Fixed SSL: CERTIFICATE_VERIFY_FAILED error

### PR DESCRIPTION
**Pull request by timdreier**
Based on this issue: https://github.com/boto/boto3/issues/2686

### CODE REVIEW

**Comment by opravdin** [comment]
Looks like it is the fix we need! I will test it on my device this evening and will merge it asap

**Comment by timdreier** [comment]
Any update @opravdin? Let me know if there's something I can do!

**Comment by timdreier** [comment]
Just tested and realised I forgot this fix in the publish_device_msg function. After that I was able to setup the extension and control my tesvor from the test environment!

**Comment by opravdin** [comment]
Sorry for delay. I have checked this fix today and that was totally fine! Thank you!

**Pull request merged**
