### PR TITLE
Update vacuum.py

### PR DESCRIPTION
**Pull request by dinki**
Add 'SmartClean' state for use with Tesvor S6

### CODE REVIEW

**Comment by dinki** [comment]
@opravdin Can you tell me what I need to do to be able to use this updated version?  Should the integration load the new code when I reboot?  I've tried and it still does not show the status as cleaning.

**Comment by opravdin** [comment]
> @opravdin Can you tell me what I need to do to be able to use this updated version? Should the integration load the new code when I reboot? I've tried and it still does not show the status as cleaning.
I made all updates needed. HACS should catch new version. Reboot after updating 1 or 2 times

**Comment by dinki** [comment]
Not running HACS.  I've had a couple of weird experiences with it and upgrading my Docker container so I prefer to install manually.  Do I just need to remove the integration, redownload, and reinstall?

**Comment by opravdin** [comment]
I should update pypi repository with new package version, will do it in couple of hours From: Chuck ConnorsSent: 19 октября 2020 г. 19:05To: opravdin/weback-unofficialCc: Pravdin Oleg; MentionSubject: Re: [opravdin/weback-unofficial] Update vacuum.py (#6) Not running HACS. I've had a couple of weird experiences with it and upgrading my Docker container so I prefer to install manually. Do I just need to remove the integration, redownload, and reinstall?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Pull request merged**
